language: python
dist: trusty
python:
    - "2.7"
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
env:
     - PARA=no
install:
     - ./configure --enable-parallel=$PARA --with-netlib --enable-xml --enable-dtr
script:
     - make all vdw_kernels
git:
  depth: 3

