language: python
python:
    - "2.7"
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
env:
     - PARA=yes
     - PARA=no
install:
     - ./configure --enable-parallel=$PARA --with-netlib --enable-xml
     - make pw
script:
    - make travis
git:
  depth: 3

